### ISSUE TITLE
Actividad 5

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-SandyMarissaGs#1]
[TIPOS DE TEXTO CUADRO COMPARATIVO Sandy M. .pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-SandyMarissaGs/files/9637639/TIPOS.DE.TEXTO.CUADRO.COMPARATIVO.Sandy.M.pdf)
Actividad 5.
Sandy Marissa García Santiago.
Grupo:1BS

**Comment by YaelTrinidad** [comment]
ACT 5 CUADRO COMPARATIVO
 "CARACTERISTICAS Y ESTRUCTURAS DE LOS TEXTOS"
DEL 20% DE LA ACTIVIDAD, DADA LA RUBRICA OBTUVISTE EL  17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
